// angular-clase/src/app/product-list/product-list.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { products } from "../mock-products";

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.scss']
})
export class ProductListComponent implements OnInit {
  products = products;
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="wrapper">
  <h1>Products</h1>
  <div>
    <div appTooltip>
      <i class="material-icons">
        list
      </i>
      <span class="tooltip">
        List view
      </span>
    </div>

    <div appTooltip>
      <i appTooltip class="material-icons">
        view_module
      </i>
      <span class="tooltip">
        Grid view
      </span>
    </div>
  </div>

  <ul>
    <li *ngFor="let product of products">
      <img [src]="product.image" [alt]="product.name">
      <div>
        <h3>{{product.name}}</h3>
        <p>{{product.description}}</p>
        <p>{{product.price}}€</p>
        <button>Add to cart</button>
      </div>
    </li>
  </ul>
</div>

// first-react/src/product-list/ProductList.jsx
import React from 'react';
import './ProductList.css';

function ProductList(props) {
    const productList = props.products.map((product) => {
        return (
            <li key={product.id}>
                <h2>{product.name}</h2>
                <img src={product.image} alt={product.name}/>
                <p>
                    {product.description.length > 150 ? (product.description.slice(0, 150)) + '...' : product.description}
                </p>
                <div className="price">{product.price} €</div>
                <div>
                <button className="button">Add to cart</button>
                </div>
            </li>
            );
    });

    return (
        <div>
            <div class="views">
            <i class="material-icons" appTooltip="list view" >
                view_list
            </i>
            <i class="material-icons" appTooltip="grid view" >
                view_module
            </i>
        </div>
        <ul>
            {productList}
        </ul>
        </div>
    );
}

export default ProductList;
